!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(userDev, "Developer", "Continuous Feedback from System")
Person(userAlias, "User/Reader", "As a new user/reader I want to join the Book Repository to store details about my books so that I can share them with a wider audience.")
Person(adminAlias, "Admin", "As an admin or user/reader with the Admin Role I want to manage the users, genres, books, and statistics so that I can provide the best possible Book Repository experience for the users/readers.")
System_Boundary(c1, "Shared Features") {
    Container(application_log, "Application Log", "Rotating File Handler for local application logs, and Heroku Console otherwise")
    Container(flash_messages, "Flash Messages", "Continuous User/Reader feedback")
    Container(fdt, "Flash Debug Toolbar", "Debugging: Request Variables, Config, Templates, Route List, Profiler")
    Container(error_handlers, "Error Handlers", "Error Handlers for 400 CSRF Error (Bad Request), 404 Page Not Found, 405 Method Not Allowed, and 500 Internal Server Error")
    Container(runtime, "Runtime", "Development (Debug) or Production")
    Container(localFile, "Log File", "Development (Debug) or Production")
    Container(csrf, "CSRF", "CSRF Token for Flask-User and Book Repository (separate)")
    Container(session, "Session", "User Book Search Criteria and MongoEngineSession Data")
}
Container(herokuConsole, "Heroku Console", "Development (Debug) or Production")
Container(gmail, "GMail", "GMail 2FA", "Registration confirmation and password reset.")
Rel_D(c1, gmail, "Uses", "SMTP")
Rel_U(flash_messages, userAlias, "Flash Messages", "Materialize Chip")
Rel_U(flash_messages, adminAlias, "Flash Messages", "Materialize Chip")
Rel_U(flash_messages, userDev, "Flash Messages", "Materialize Chip")
Rel_U(fdt, userDev, "Debug", "Detailed debug information about Flask")
Rel_U(application_log, localFile, "Application Log to File", "Debug to Critical")
Rel_U(localFile, userDev, "Event Analyis", "Debug to Critical")
Rel_U(application_log, herokuConsole, "Application Log to Heroku Console", "Debug to Critical")
Rel_U(herokuConsole, userDev, "Event Analysis", "Debug to Critical")
Rel_U(runtime, userDev, "Application Debug", "Debug level information from WSGI/Gunicorn")
Rel_U(error_handlers, userAlias, "Client and Server Errors", "Error Handlers for 400 CSRF Error (Bad Request), 404 Page Not Found, 405 Method Not Allowed, and 500 Internal Server Error")
Rel_U(error_handlers, adminAlias, "Client and Server Errors", "Error Handlers for 400 CSRF Error (Bad Request), 404 Page Not Found, 405 Method Not Allowed, and 500 Internal Server Error")
Rel_U(error_handlers, userDev, "Client and Server Errors", "Error Handlers for 400 CSRF Error (Bad Request), 404 Page Not Found, 405 Method Not Allowed, and 500 Internal Server Error")
Rel_U(csrf, userAlias, "CSRF", "Flask-User and Book Repository templates")
Rel_U(csrf, adminAlias, "CSRF", "Flask-User and Book Repository templates")
Rel_U(csrf, userDev, "CSRF", "Flask-User and Book Repository templates")
Rel_U(session, userAlias, "Session Cookies and MongoDB", "Session Cookies and Book Search Criteria")
Rel_U(session, adminAlias, "Session Cookies and MongoDB", "Session Cookies and Book Search Criteria")
Rel_U(session, userDev, "Session Cookies and MongoDB", "Session Cookies and Book Search Criteria")